name: Update README

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update README with GitHub activity
        uses: Shyam-Vishwakarma/github-footprints@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_LINES: 5
          TARGET_FILE: README.md
          TRACK_EVENTS: "PullRequestEvent,IssuesEvent"
